python -m main \
    --images_dir "datasets/images/leftImg8bit/" \
    --labels_dir "datasets/labels/gtFine" \
    --seed 42 \
    --device_type "cuda" \
    --image_height 224 \
    --image_width 224 \
    --in_channels 3 \
    --ignore_void_classes True \
    --batch_size 4 \
    --num_workers 2 \
    --shuffle True \
    --drop_last False \
    --model_name "Unet" \
    --encoder_name "resnet34" \
    --encoder_depth 5 \
    --encoder_weights "imagenet" \
    --num_classes 19 \
    --output_dir "outputs" \
    --log_path "logs" \
    --model_save_path "models" \
    --num_epochs 100 \
    --steps_per_log 10 \
    --learning_rate 0.05 \
    --save_model_every 10 \
    --experiment_name 'tdt14_project'
